#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# This file is part of MPIS (https://github.com/KernelPanicBlog/MPIS-QT).
#
# MPIS-QT(Manjaro Post Installation Script GUI QT) is free software; you can
# redistribute it and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; either version 3 of
# the License,or any later version.
#
# MPIS-QT (Manjaro Post Installation Script) GUI QT:
# It allows  users to choose different options such as
# install an application or config some tools and environments.
#
# MPIS-QT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with MPIS-QT; If not, see <http://www.gnu.org/licenses/>.
###############################################################################
import mpislib
import subprocess
from mpisqtlib.gui.main import MpisQt

ver = mpislib.__version__
checkver = float(ver[:3])

if checkver >= 0.3:
    import sys
    from PyQt4.QtGui import QApplication

    process = "notify-send"
    strmsg = """Thanks for choosing us.
     We hope this script helped you.
          -The KernelPanicBlog Team.
    Our web: https://kernelpanicblog.wordpress.com"""

    subprocess.call([process, strmsg])

    app = QApplication(sys.argv)

    mpis_qt = MpisQt()
    mpis_qt.show()
    sys.exit(app.exec_())
else:
    process = "notify-send"
    strmsg = "this App Requiered MPIS version > 0.3 or "
    subprocess.call([process, strmsg])
